// resources/js/components/List.jsx
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { getFetch } from '../helper_react';

const RenderProducts = () => {

    // Tároló és feldolgozó definiálása
    const [items, setItems] = useState([]);

    // Elemek lekérdezése
    useEffect(() => {
        getFetch('/api/list', setItems);
    }, []);

    // Visszatérés a táblázattal
    return (
        <div className="row gallery">
            {items.map((item,index) => (
                <div className="col-sm-2 text-center" key={index}>
                    <p className="fw-bold">{ item.name }</p>
                    <img src={ item.image } className="img-thumbnail"/>
                    <p>
                        { item.discount_price }<br/>
                        <a href={"/react/product/"+item.id} className="btn btn-primary">Megtekintés</a>
                    </p>
                </div>
            ))}
        </div>
    );

};

// Tartalom
function List() {
    return (
        <div>
            <h1>Termékek listája</h1>
            <RenderProducts/>
        </div>
    );
}

// Tartalom betöltése
export default List;

if (document.getElementById('list')) {
    const Index = ReactDOM.createRoot(document.getElementById("list"));
    Index.render(
        <React.StrictMode>
            <List/>
        </React.StrictMode>
    )
}

// resources/js/pages/List.vue
<template>
    <h1>Termékek listája</h1>
    <div class="row gallery">
        <div v-for="item in list" class="col-sm-2 text-center" @click="openProduct(item.id)">
            <p class="fw-bold">{{ item.name }}</p>
            <img :src="item.image" class="img-thumbnail"/>
            <p>
                {{ item.discount_price }}<br>
                <button class="btn btn-primary">Megtekintés</button>
            </p>
        </div>
    </div>
</template>
<script>
// Importálás
import {request} from '../helper'
import {ref, onMounted} from 'vue'
import router from '../route'

// Exportálás
export default {
    setup() {
        let list = ref({});
        let response = ref(null);

        // Amikor betöltődött az oldal
        onMounted(() => {
            getList();
        });

        // Termékek listájának lekérdezése
        const getList = async () => {

            try {
                // GET kérés küldése a szervernek
                response = await request('get', '/api/list');

                // Adatok lekérdezése és megjelenítése
                list.value = response.data;

            } catch (error) {
                console.log(error);
            }
        }

        // Termék oldal megnyitása
        const openProduct = async(id) => {
            router.push('/vue/product/'+id);
        }

        return {
            getList,
            openProduct,
            list
        }
    }
}
</script>
