// resources/js/pages/User.vue
<template>
    <h1>Felhasználó adatai</h1>
    <input type="hidden" v-model="user.id"/>
    <div class="row mb-2">
        <div class="col-sm-3">Felhasználói név</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.name"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Vezetéknév</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.surname"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Keresztnév</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.forename"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Ország</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.country"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Területi egység</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.state"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Irányítószám</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.zip"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Település</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.city"/>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-3">Utca, házszám...</div>
        <div class="col-sm-9">
            <input type="text" class="form-control" v-model="user.address"/>
        </div>
    </div>
    <div>
        <button class="btn btn-primary" @click="saveUser" v-show="result.button">Mentés</button>
        <div class="alert alert-success" role="alert" v-show="result.success">
            Sikeres művelet!
        </div>
        <div class="alert alert-danger" role="alert" v-show="result.error"><span v-html="result.message"></span></div>
    </div>
</template>
<script>
// Importálás
import {request} from '../helper'
import {ref, onMounted} from 'vue'

// Exportálás
export default {
    setup() {
        
        // Elemekre történő hivatkozások megadása
        let response = ref(null);
        let user = ref({
            id:  null,
            name:  null,
            surname:  null,
            forename:  null,
            country:  null,
            state:  null,
            zip:  null,
            city:  null,
            address:  null
        });
        let result = ref({
            success: false,
            error: false,
            button: true,
            message: null
        });

        // Amikor betöltődött az oldal
        onMounted(() => {
            getUser();
        });

        // Felhasználó adatainak lekérdezése
        const getUser = async () => {
            try {
                // GET kérés küldése a szervernek
                response = await request('get', '/api/vue/user');

                // Mezők értékeinek megadása a kérés eredménye alapján
                user.value = response.data;
            } catch (error) {
                console.log(error);
            }
        }

        // Felhasználó adatainak mentése
        const saveUser = async () => {
            try {

                // Mezők értékeinek lekérdezése
                const data = {
                    id: user.value.id,
                    name: user.value.name,
                    surname: user.value.surname,
                    forename: user.value.forename,
                    country: user.value.country,
                    state: user.value.state,
                    zip: user.value.zip,
                    city: user.value.city,
                    address: user.value.address
                }

                // Kérés küldése a szerver felé
                const response = await request('post', '/api/vue/user', data);
                
                // Ha OK = 1 a válasz
                if (response.data.OK == 1) {

                    // Eredmény mutatása
                    result.value = { success: true, error: false, button: false, message: null }

                }
            } catch (error) {

                // Hibák lekérdezése
                let errors = error.response.data.errors;

                // Hibaszöveg létrehozása ezen hibákból
                let errorMessage = Object.values(errors).join("<br>");

                // Hiba mutatása
                result.value = { success: false, error: true, button: false, message: errorMessage }
                
            }

            // 3 másodperc múlva az eredmény elrejtése
            setTimeout(function() {
                result.value = { success: false, error: false, button: true, message: null }
            }, 3000);
        }

        // Visszatérés
        return {
            user,
            result,
            getUser,
            saveUser
        }
    }
}
</script>

// resources/js/components/User.jsx
import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { getFetch, setFetch } from '../helper_react';

const RenderUser = () => {

    // Definiálás
    const [user, setUser] = useState([]);

    // Elemek lekérdezése
    useEffect(() => {

        getFetch('/api/user', setUser);

    }, []);

    const forceChange = (form) => {
        [...form.elements].map(element => {
            const name = element.name;
            const value = element.value;
            setInputs(values => ({...values, [name]: value}));
        })
    }

    const [inputs, setInputs] = useState(user);

    const handleSubmit = (event) => {
        event.preventDefault();
        forceChange(event.target);
        console.log(inputs);
    }

    // Visszatérés a táblázattal
    return (
        <form onSubmit={handleSubmit}>
            <input type="hidden" name="id" defaultValue={user.id}/>
            <div className="row mb-2">
                <div className="col-sm-3">Felhasználói név</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="name"  defaultValue={user.name}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Vezetéknév</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="surname" defaultValue={user.surname}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Keresztnév</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="forename" defaultValue={user.forename}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Ország</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="country" defaultValue={user.country}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Területi egység</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="state" defaultValue={user.state}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Irányítószám</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="zip" defaultValue={user.zip}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Település</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="city" defaultValue={user.city}/>
                </div>
            </div>
            <div className="row mb-2">
                <div className="col-sm-3">Utca, házszám...</div>
                <div className="col-sm-9">
                    <input type="text" className="form-control" name="address" defaultValue={user.address}/>
                </div>
            </div>  
            <button className="btn btn-primary">Mentés</button>
        </form> 
    );

};

const RenderAnswer = (data) => {

    // Definiálás
    const [response, setResponse] = useState([]);

    useEffect(() => {
        setFetch("/api/user", data, setResponse)
    }, []);

    if (response.OK==1) {
        return (
            <div className="alert alert-success" role="alert">
                Sikeres művelet!
            </div>
        )
    } else {
        return (
            <div className="alert alert-danger" role="alert">
                <ul>
                    {response.data.errors.map((item,index) => (
                        <li key={index}>{item}</li>
                    ))}
                </ul>
            </div>
        )
    }
}

// Tartalom
function User() {
    return (
        <div>
            <h1>Felhasználó adatai</h1>
            <RenderUser/>
        </div>
    );
}

// Tartalom betöltése
export default User;

if (document.getElementById('user')) {
    const Index = ReactDOM.createRoot(document.getElementById("user"));
    Index.render(
        <React.StrictMode>
            <User/>
        </React.StrictMode>
    )
}
